// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MovePlayersHandler(ReducerEventContext ctx, MovePlayersSchedule timer);
        public event MovePlayersHandler? OnMovePlayers;

        public void MovePlayers(MovePlayersSchedule timer)
        {
            conn.InternalCallReducer(new Reducer.MovePlayers(timer), this.SetCallReducerFlags.MovePlayersFlags);
        }

        public bool InvokeMovePlayers(ReducerEventContext ctx, Reducer.MovePlayers args)
        {
            if (OnMovePlayers == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMovePlayers(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MovePlayers : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public MovePlayersSchedule Timer;

            public MovePlayers(MovePlayersSchedule Timer)
            {
                this.Timer = Timer;
            }

            public MovePlayers()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "MovePlayers";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MovePlayersFlags;
        public void MovePlayers(CallReducerFlags flags) => MovePlayersFlags = flags;
    }
}
