// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetHandler(ReducerEventContext ctx, string newName);
        public event SetHandler? OnSet;

        public void Set(string newName)
        {
            conn.InternalCallReducer(new Reducer.Set(newName), this.SetCallReducerFlags.SetFlags);
        }

        public bool InvokeSet(ReducerEventContext ctx, Reducer.Set args)
        {
            if (OnSet == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSet(
                ctx,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Set : Reducer, IReducerArgs
        {
            [DataMember(Name = "newName")]
            public string NewName;

            public Set(string NewName)
            {
                this.NewName = NewName;
            }

            public Set()
            {
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "Set";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetFlags;
        public void Set(CallReducerFlags flags) => SetFlags = flags;
    }
}
