// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "EntityId")]
        public uint EntityId;
        [DataMember(Name = "Position")]
        public SpacetimeVector3 Position;

        public Entity(
            uint EntityId,
            SpacetimeVector3 Position
        )
        {
            this.EntityId = EntityId;
            this.Position = Position;
        }

        public Entity()
        {
            this.Position = new();
        }
    }
}
