// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "EntityId")]
        public uint EntityId;
        [DataMember(Name = "UserId")]
        public uint UserId;
        [DataMember(Name = "Direction")]
        public SpacetimeVector3 Direction;
        [DataMember(Name = "Speed")]
        public float Speed;

        public Player(
            uint EntityId,
            uint UserId,
            SpacetimeVector3 Direction,
            float Speed
        )
        {
            this.EntityId = EntityId;
            this.UserId = UserId;
            this.Direction = Direction;
            this.Speed = Speed;
        }

        public Player()
        {
            this.Direction = new();
        }
    }
}
