// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ServerWorldConfig
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "WorldSize")]
        public ulong WorldSize;

        public ServerWorldConfig(
            uint Id,
            ulong WorldSize
        )
        {
            this.Id = Id;
            this.WorldSize = WorldSize;
        }

        public ServerWorldConfig()
        {
        }
    }
}
