// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MovePlayersSchedulesHandle : RemoteTableHandle<EventContext, MovePlayersSchedule>
        {
            protected override string RemoteTableName => "MovePlayersSchedules";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MovePlayersSchedule row) => row.Id;

                public IdUniqueIndex(MovePlayersSchedulesHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal MovePlayersSchedulesHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(MovePlayersSchedule row) => row.Id;
        }

        public readonly MovePlayersSchedulesHandle MovePlayersSchedules;
    }
}
