// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayersHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "Players";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Player row) => row.EntityId;

                public EntityIdUniqueIndex(PlayersHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class UserIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Player row) => row.UserId;

                public UserIdIndex(PlayersHandle table) : base(table) { }
            }

            public readonly UserIdIndex UserId;

            internal PlayersHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                UserId = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.EntityId;
        }

        public readonly PlayersHandle Players;
    }
}
