// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldsHandle : RemoteTableHandle<EventContext, ServerWorldConfig>
        {
            protected override string RemoteTableName => "Worlds";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ServerWorldConfig row) => row.Id;

                public IdUniqueIndex(WorldsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ServerWorldConfig row) => row.Id;
        }

        public readonly WorldsHandle Worlds;
    }
}
